apache/incubator-graphar

.gitmodules, README.rst, docs/user-guide/getting-started.rst
Signed-off-by: acezen <qiaozi.zwb@alibaba-inc.com>
=> Update gar-test submodule url

include/gar/graph_info.h, spark/src/main/scala/com/alibaba/graphar/EdgeReader.scala, spark/src/main/scala/com/alibaba/graphar/VertexReader.scala, spark/src/main/scala/com/alibaba/graphar/reader/EdgeReader.scala, spark/src/main/scala/com/alibaba/graphar/reader/VertexReader.scala, spark/src/main/scala/com/alibaba/graphar/utils/IndexGenerator.scala, spark/src/test/scala/com/alibaba/graphar/TestReader.scala, test/test_info.cc
Initialize implementation for spark readers, which could read GAR files into Spark DataFrame.
Fixed issue: #29
=> Initialize implementation for spark reader

README.rst, docs/applications/bgl.rst, docs/applications/graphscope.rst, docs/applications/out-of-core.rst, docs/user-guide/file-format.rst, docs/user-guide/getting-started.rst, docs/user-guide/overview.rst, docs/user-guide/spark-lib.rst
This change refines the user guide  and applications pages in GraphAr's documentation, improving writing and fixing some issues.
fix issue #65
=> [Improve][Doc] Refine the documentation about user guide and applications

.github/workflows/spark.yaml, spark/src/main/scala/com/alibaba/graphar/reader/EdgeReader.scala, spark/src/main/scala/com/alibaba/graphar/reader/VertexReader.scala, spark/src/main/scala/com/alibaba/graphar/utils/FileSystem.scala, spark/src/test/scala/com/alibaba/graphar/TestReader.scala, src/filesystem.cc
Enable the feature that write CSV payload files with header to provide some of meta data of graph for reader.
Fixed issue: #60
=> [Improvement][FileFormat] Write CSV payload files with header

.github/workflows/docs.yml
Do comments as expected by leveraging the `pull_request_target` feature.
=> Handle comments correctly for preview PR docs

spark/src/main/scala/com/alibaba/graphar/utils/IndexGenerator.scala, spark/src/main/scala/com/alibaba/graphar/writer/EdgeWriter.scala, spark/src/main/scala/com/alibaba/graphar/writer/VertexWriter.scala
=> [BugFix] Fix the Spark Writer bug when the column name contains a dot(.)

docs/applications/graphscope.rst
=> [Minor] Update the source code url of GraphScope fragment builder and writer

cpp/examples/config.h
=> [Minor][BugFix] Fix test data path for examples

README.rst
=> [Minor] Update README: add information about weekly meeting

.gitmodules, LICENSE, cpp/CMakeLists.txt, cpp/include/gar/utils/yaml.h, cpp/src/graph_info.cc, cpp/src/yaml.cc, cpp/test/test_info.cc, cpp/thirdparty/mini-yaml/yaml/Yaml.cpp, cpp/thirdparty/mini-yaml/yaml/Yaml.hpp
Use a single header yaml library like mini-yaml to avoid initialize submodule recursive
Fix issue #141
=> [FEAT] Use single header yaml parser `mini-yaml`

README.rst, docs/user-guide/file-format.rst, docs/user-guide/getting-started.rst, docs/user-guide/spark-lib.rst
Refine and improve the introduction of the [GraphAr file format](https://alibaba.github.io/GraphAr/user-guide/file-format.html) design, to make it more clear and easy to understand for beginners.
related to issue #159
=> [Doc] Refine the documentation about the file format of GraphAr

cpp/README.rst, cpp/test/test_arrow_chunk_writer.cc, docs/user-guide/getting-started.rst, spark/src/main/scala/com/alibaba/graphar/EdgeInfo.scala, spark/src/main/scala/com/alibaba/graphar/VertexInfo.scala, spark/src/main/scala/com/alibaba/graphar/reader/EdgeReader.scala, spark/src/test/scala/com/alibaba/graphar/TestReader.scala, spark/src/test/scala/com/alibaba/graphar/TransformExample.scala
Hi! I'm fresh for GraphAr, I found some docs improvment when I make a quick start about Reader SDK.
=> [Doc] Improve spelling

cpp/src/arrow_chunk_writer.cc
=> [Improvement][C++] Use recommended parameter to sort in Writer

cpp/include/gar/reader/arrow_chunk_reader.h, cpp/include/gar/reader/chunk_info_reader.h, cpp/src/reader_utils.cc
Make the messages more consistent with conditions.
=> [Improvement][C++] Refine the error message of Reader SDK

cpp/include/gar/graph_info.h
=> [Doc][C++] Refine document comments in graph_info.h

spark/README.md
=> [Spark][Doc]Add java version for neo4j example.

cpp/include/gar/graph_info.h
=> Fix grammar mistakes.

docs/requirements.txt
=> [Minor] Fix the broken CI of doc

spark/pom.xml
=> [BugFix][Spark] Fix compile error under JDK8

README.rst
=> chore: fix readme example typo

spark/.scalafix.conf, spark/pom.xml, spark/src/main/scala/com/alibaba/graphar/EdgeInfo.scala, spark/src/main/scala/com/alibaba/graphar/GraphInfo.scala, spark/src/main/scala/com/alibaba/graphar/VertexInfo.scala, spark/src/main/scala/com/alibaba/graphar/datasources/GarCommitProtocol.scala, spark/src/main/scala/com/alibaba/graphar/datasources/GarDataSource.scala, spark/src/main/scala/com/alibaba/graphar/datasources/GarWriterBuilder.scala, spark/src/main/scala/com/alibaba/graphar/datasources/csv/CSVWriterBuilder.scala, spark/src/main/scala/com/alibaba/graphar/example/GraphAr2Neo4j.scala, spark/src/main/scala/com/alibaba/graphar/example/Neo4j2GraphAr.scala, spark/src/main/scala/com/alibaba/graphar/graph/GraphReader.scala, spark/src/main/scala/com/alibaba/graphar/graph/GraphTransformer.scala, spark/src/main/scala/com/alibaba/graphar/graph/GraphWriter.scala, spark/src/main/scala/com/alibaba/graphar/reader/EdgeReader.scala, spark/src/main/scala/com/alibaba/graphar/reader/VertexReader.scala, spark/src/main/scala/com/alibaba/graphar/util/DataFrameConcat.scala, spark/src/main/scala/com/alibaba/graphar/util/FileSystem.scala, spark/src/main/scala/com/alibaba/graphar/util/IndexGenerator.scala, spark/src/main/scala/com/alibaba/graphar/util/Patitioner.scala, spark/src/main/scala/com/alibaba/graphar/writer/EdgeWriter.scala, spark/src/main/scala/com/alibaba/graphar/writer/VertexWriter.scala, spark/src/test/scala/com/alibaba/graphar/ComputeExample.scala, spark/src/test/scala/com/alibaba/graphar/TestGraphInfo.scala, spark/src/test/scala/com/alibaba/graphar/TestGraphReader.scala, spark/src/test/scala/com/alibaba/graphar/TestGraphTransformer.scala, spark/src/test/scala/com/alibaba/graphar/TestGraphWriter.scala, spark/src/test/scala/com/alibaba/graphar/TestIndexGenerator.scala, spark/src/test/scala/com/alibaba/graphar/TestWriter.scala, spark/src/test/scala/com/alibaba/graphar/TransformExample.scala
add scalafix plugin to remove unused import: https://github.com/evis/scalafix-maven-plugin
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, …
=> chore: remove unused import

docs/user-guide/spark-lib.rst, spark/README.md, spark/pom.xml
=> [Minor][Spark] Support get GraphAr Spark from Maven

cpp/examples/config.h
=> [Bugfix] Fix testing data path of examples

dev/release-process.md
Since road map is a high level vision of GraphAr, we need a document to explain the release process and milestone detail, as a supplement of road map。
=> [Minor][Doc] Add release-process.md to explain the release process

spark/src/main/scala/com/alibaba/graphar/util/FileSystem.scala
=> [Spark][Bugfix] Close the FileSystem Object

java/CMakeLists.txt
detail in the issue #260 
close #260
=> [BugFix][JAVA] Fix the building order bug of java SDK

.github/workflows/ci-nightly.yml, cpp/CMakeLists.txt
=> [Improve][C++] Use arrow shared library if arrow installed

docs/Makefile
=> [Doc][BugFix] Fix missing of scaladoc and javadoc in website

cpp/include/gar/writer/arrow_chunk_writer.h, cpp/include/gar/writer/edges_builder.h, cpp/include/gar/writer/vertices_builder.h
=> [Minor][Doc] Fix the typos of document

docs/user-guide/java-lib.rst, java/CMakeLists.txt, java/README.md, java/pom.xml
=> [BugFix][Java]: Fix invalid option to skip building GraphAr C++ internally for java

cpp/include/gar/graph_info.h, cpp/include/gar/util/util.h
=> [Minor][C++] Fix typo: REGULAR_SEPERATOR -> REGULAR_SEPARATOR

docs/cpp/reference/index.rst
=> [Minor][Doc] Fix the cpp reference

.github/PULL_REQUEST_TEMPLATE.md
Update the PR template that remove the `Type of change` that already indicated in title.
=> [Minor][Dev] Update the pr template

java/pom.xml, spark/pom.xml
Since mvn use maven-site-plugin 3.3 and there is a [bug](https://issues.apache.org/jira/browse/MRELEASE-1052), update the version to 3.7.1
close issue #304
=> [BugFix][Spark] change maven-site-plugin to 3.7.1

cpp/src/graph_info.cc
=> [Minor][C++] Improve the validation check of info

.github/workflows/java.yml, docs/developers/java-dev.rst, java/src/test/java/com/alibaba/graphar/edges/EdgesCollectionTest.java, java/src/test/java/com/alibaba/graphar/graphinfo/GraphInfoTest.java, java/src/test/java/com/alibaba/graphar/vertices/VerticesCollectionTest.java, java/src/test/java/com/alibaba/graphar/writers/VertexPropertyWriterTest.java
Get test resources form environment variables, and remove all print sentences
close #308 .
=> [Improve][Java] Get test resources form environment variables, and remove all print sentences

spark/pom.xml, spark/src/main/scala/com/alibaba/graphar/EdgeInfo.scala, spark/src/main/scala/com/alibaba/graphar/GraphInfo.scala, spark/src/main/scala/com/alibaba/graphar/VertexInfo.scala
Update snakeyaml as discussed in #311 
Just few lines of changes.
=> [Feat][Spark] Update snakeyaml to 2.x.x version

.github/workflows/ci.yml, cpp/CMakeLists.txt, cpp/README.md, cpp/benchmarks/arrow_chunk_reader_benchmark.cc, cpp/benchmarks/benchmark_util.h, cpp/benchmarks/graph_info_benchmark.cc
This change initialize the micro benchmark for c++, only support graph info and arrow chunk reader, will be add more in the future.
close issue #288
=> [Feat][C++] Initialize the micro benchmark for c++

spark/src/main/scala/com/alibaba/graphar/graph/GraphWriter.scala, spark/src/main/scala/com/alibaba/graphar/writer/VertexWriter.scala
Changes in constructor of `VertexWriter` as we discussed in #313 
Close #313 
Related to #300
=> Change VertexWriter constructor signature

spark/src/main/scala/com/alibaba/graphar/util/Utils.scala
=> [Minor][Spark] Fix Spark comparison bug

.github/workflows/ci-nightly.yml, .github/workflows/pyspark.yml, .github/workflows/release.yml
=> [Minor][Dev] Update release workflow to make release easy and revise other workflows

docs/cpp/getting-started.rst
=> [Minor][Doc] Update getting-started.rst to fix a typo

spark/src/main/java/com/alibaba/graphar/GeneralParams.java, spark/src/main/scala/com/alibaba/graphar/EdgeInfo.scala, spark/src/main/scala/com/alibaba/graphar/GraphInfo.scala, spark/src/main/scala/com/alibaba/graphar/VertexInfo.scala
=> [Minor][Spark] Fix typo

README.rst
=> [Minor][Doc] Remove unused community channel and add publication citation

README.rst
Fix the format  error include by #331 of README
=> [Minor][Doc] Fix README

cpp/src/graph.cc
As title. 
close #341 
Also, I think there needs a test contains the check of all types.
=> [Bug][C++] Add implement of property<bool>

cpp/src/graph.cc
=> [Chore][C++] fix err message

README.rst
=> [Minor][Doc] Update publication information and fix link in ReadMe

cpp/include/gar/fwd.h
Minor fix typo of cpp reference
=> [Minor][Doc] Minor fix typo of cpp reference

cpp/include/gar/fwd.h, cpp/include/gar/graph_info.h, docs/cpp/reference/index.rst
Complement the api reference document of cpp
=> [Improvement][Doc][CPP] Complement the api reference document of cpp

docs/spark/spark-lib.rst, spark/README.md
=> [Feat][Doc] update Spark documentation by introducing Maven Profiles

docs/format/file-format.rst
Fix the link of images in format document which break by PR #373 
=> [Minor][Doc] Fix the link of the images

cpp/src/arrow_chunk_writer.cc
as issue #408 describe
close #408
=> [FEAT][C++] Enhance the validation of writer with arrow::Table's Validate

.licenserc.yaml, DISCLAIMER, NOTICE
=> chore: add NOTICE and DISCLAIMER

docs/spark/spark-lib.rst, spark/README.md
Since the branch `mvn-repo` is deleted, the maven install document is validation, we should remove it.
=> [Improvement][Doc] Remove the invalid maven package doc

.gitmodules, cpp/include/gar/graph.h, cpp/src/graph.cc, cpp/test/test_graph.cc, docs/cpp/getting-started.rst
Related to #434
If it works, i will add test case for it.
=> [Feat][C++] Add isValid for property in high level

.asf.yaml
related to #440
The configuration specifies:
- description
- labels
- hompage
- github setting
- notification
=> [Apache][Infra] Add configuration yaml file for main branch

spark/graphar/src/main/java/org/apache/graphar/info/EdgeInfo.java, spark/graphar/src/main/java/org/apache/graphar/info/GraphInfo.java, spark/graphar/src/main/java/org/apache/graphar/info/PropertyGroup.java, spark/graphar/src/main/java/org/apache/graphar/info/VertexInfo.java, spark/graphar/src/main/java/org/apache/graphar/info/type/AdjListType.java, spark/graphar/src/main/java/org/apache/graphar/info/yaml/AdjacentListYamlParser.java, spark/graphar/src/main/java/org/apache/graphar/info/yaml/EdgeYamlParser.java, spark/graphar/src/main/java/org/apache/graphar/info/yaml/GraphYamlParser.java, spark/graphar/src/main/java/org/apache/graphar/info/yaml/PropertyGroupYamlParser.java, spark/graphar/src/main/java/org/apache/graphar/info/yaml/PropertyYamlParser.java, spark/graphar/src/main/java/org/apache/graphar/info/yaml/VertexYamlParser.java
Main changes:
- prefix and file get methods for info;
- dump and save methods for info;
- dump-related methods for yamlParser;
Related issue #441
=> [Spark-java-refactor] Implement file get, dump and save functions for info

pyspark/Makefile, pyspark/graphar_pyspark/info.py, pyspark/graphar_pyspark/reader.py, pyspark/graphar_pyspark/util.py, pyspark/graphar_pyspark/writer.py, pyspark/pyproject.toml, pyspark/tests/__init__.py, pyspark/tests/conftest.py, pyspark/tests/test_enums.py, pyspark/tests/test_info.py, pyspark/tests/test_reader.py, pyspark/tests/test_transform.py, pyspark/tests/test_writer.py
=> chore: fix the header of pyspark source code

docs/libraries/cpp/examples/snap-to-graphar.md, docs/libraries/cpp/getting-started.md, docs/libraries/java/java.md, docs/libraries/pyspark/how-to.md, docs/libraries/spark/examples.md, docs/libraries/spark/spark.md, docs/specification/format.md
=> [Minor][Doc] Fix issues in the documentation

spark/datasources-32/src/main/scala/org/apache/graphar/datasources/GarCommitProtocol.scala, spark/datasources-32/src/main/scala/org/apache/graphar/datasources/GarDataSource.scala, spark/datasources-32/src/main/scala/org/apache/graphar/datasources/GarScan.scala, spark/datasources-32/src/main/scala/org/apache/graphar/datasources/GarScanBuilder.scala, spark/datasources-32/src/main/scala/org/apache/graphar/datasources/GarTable.scala, spark/datasources-32/src/main/scala/org/apache/graphar/datasources/GarWriterBuilder.scala, spark/datasources-32/src/main/scala/org/apache/graphar/datasources/csv/CSVWriterBuilder.scala, spark/datasources-32/src/main/scala/org/apache/graphar/datasources/orc/OrcOutputWriter.scala, spark/datasources-32/src/main/scala/org/apache/graphar/datasources/orc/OrcWriteBuilder.scala, spark/datasources-32/src/main/scala/org/apache/graphar/datasources/parquet/ParquetWriterBuilder.scala, spark/datasources-33/src/main/scala/org/apache/graphar/datasources/GarCommitProtocol.scala, spark/datasources-33/src/main/scala/org/apache/graphar/datasources/GarDataSource.scala, spark/datasources-33/src/main/scala/org/apache/graphar/datasources/GarScan.scala, spark/datasources-33/src/main/scala/org/apache/graphar/datasources/GarScanBuilder.scala, spark/datasources-33/src/main/scala/org/apache/graphar/datasources/GarTable.scala, spark/datasources-33/src/main/scala/org/apache/graphar/datasources/GarWriterBuilder.scala, spark/datasources-33/src/main/scala/org/apache/graphar/datasources/csv/CSVWriterBuilder.scala, spark/datasources-33/src/main/scala/org/apache/graphar/datasources/orc/OrcOutputWriter.scala, spark/datasources-33/src/main/scala/org/apache/graphar/datasources/orc/OrcWriteBuilder.scala, spark/datasources-33/src/main/scala/org/apache/graphar/datasources/parquet/ParquetWriterBuilder.scala
Add more spark reference code link to datasource sub-package
as title
yes
no
=> chore: Add more reference code link to datasource

LICENSE, NOTICE
as issue #479 describes
for 3rd-party dependencies of graphar:
- put licence information  to LICENSE
- put notice information  to NOTICE
=> fix(license): fix LICENSE and NOTICE file according to ASF policy

.devcontainer/devcontainer.json
as #490 describe.
update the image to a valid url.
no need to test
no
=> fix(infra): Fix the invalid dev container image

.devcontainer/devcontainer.json
#490 
Update the image of initializeCommand in devcontainer.json
no
no
=> fix(dev): Update the image of initializeCommand in devcontainer.json

README.md
as title
fix readme links
yes
no
=> fix(docs): fix invalid repo links in README

.github/workflows/ci.yml, cpp/README.md
The [arrow](https://github.com/Homebrew/homebrew-core/blob/4588359b7248b07379094de5310ee7ff89afa17e/Formula/a/apache-arrow.rb#L53) in Homebrew has disable ORC support currently, which would make graphar get compile error in macos.
disable the macos ci
yes
NO
=> fix(ci): disable macos ci for the arrow library installed by brew is incomplete

docs/specification/implementation-status.md
The `json` payload file has been supported by C++/Scala/Python library in #518 , update the implement status
docs.
Update the implementation status
no need to test
No
=> chore(docs): update the implementation status

.github/workflows/ci.yml, cpp/CMakeLists.txt, cpp/README.md
=> feat(c++): support static graphar

cpp/README.md
Minor updates on cpp README file to make logic more consistent. 
- make bash code formatting consistent and copyable.
- in the dependencies section, users do not need to git clone graphar, (which is guided in the next section `Building`)
- manually build and install apache-arrow should be in the next step of installing dependencies by brew, to replace the brew installed one. I moved its position, fixed a typo, added a hint about the build option and updated the note style.
No code updated.
No code updated.
=> docs(c++): Minor updates on cpp README

CONTRIBUTING.md
=> chore: update library link

cpp/README.md
=> doc: Fix a link

maven-projects/spark/README.md
=> doc(spark): Update README.md

maven-projects/java/pom.xml
feat(Java): make maven-spotless-plugin version as a parameter
=> feat(Java): make maven-spotless-plugin version as a parameter

.github/workflows/ci.yml, cpp/CMakeLists.txt
Fixed issue #544, since now apache-arrow ORC extension is optional (by #558)
Opened CI.
Tested by CI.
No.
=> Chore(CI): Opened macOS CI

.devcontainer/devcontainer.json
To address issue #537 
Changed the default image registry.
Yes.
No.
=> chore(dev): Change default docker image registry to ghcr.

docs/libraries/spark/spark.md, maven-projects/spark/graphar/pom.xml, maven-projects/spark/pom.xml
discuss in #570 
- add related reference document about how to working with cloud storage
- remove the related oss and cupid dependencies
yes
no
=> chore(spark): Add reference document about how to integrate cloud storage and remove related dependencies

maven-projects/spark/graphar/src/main/scala/org/apache/graphar/graph/GraphWriter.scala
=> chore(spark): fix comment typo in GraphWriter.scala

cpp/src/graphar/filesystem.cc, cpp/src/graphar/filesystem.h, cpp/test/test_info.cc, docs/libraries/cpp/getting-started.md
fix issue #566 
Add a `FinalizeS3` method and related document for working AWS S3 storage with C++ SDK
yes
no
=> fix(c++): Add FinalizeS3 function to release S3 resource

maven-projects/spark/README.md
=> chore: fix typo in the Nebula example's doc

maven-projects/spark/README.md
=> docs: correct the example path

.devcontainer/Makefile
build multiple platform for dev docker image
=> chore: Build multiple platform dev image

maven-projects/spark/README.md
fix an error command in README.md
replace `GRA` with `GAR`
yes
no
=> doc(spark): fix an error command in README.md

maven-projects/info/.scalafmt.conf, maven-projects/info/pom.xml, maven-projects/java/pom.xml, maven-projects/pom.xml, maven-projects/spark/pom.xml
close #591 
reorganized the spotless maven plugin.
yes
no
=> chore(spark,java): extract format plugin into parent module

cpp/README.md
as title
Update  README.md
yes
no
=> chore(docs): Update README.md

cpp/src/graphar/filesystem.cc
=> feat(c++): close arrow::fs::InitializeS3 when arrow version <15

README.md
Revise the research branch for VLDB2025 submission.
=> revise the readme in research branch.

cpp/examples/high_level_writer_example.cc
=> chore(c++): fix a bug in high_level_writer_example.cc

.github/workflows/ci.yml
The mac version 12 install apache-arrow take a lot of time (~3h), try to use mac version 13 in CI.
=> fix(ci): Use mac version 13

.github/workflows/ci.yml
=> fix(ci): arrow 18.0.1 in ubutun got ubdefined function errors, try to revert to 17.0.0

.github/workflows/ci.yml, cli/pyproject.toml
As https://lists.apache.org/thread/4hyblyft6dp9lw8zf7mb4vdgxsothj9w mentioned, both actions/upload-artifact@v3*
and actions/download-artifact@v3* will stop working in 10 days.
upgrade to v4
=> chore(ci): Upgrade artifact actions from v3 to v4

README.md
=> update citation information

README-zh-cn.md, README.md
update information for publications
readme and its Chinese version
Yes
No
=> docs: update information for publications

cpp/README.md
#670 
Modify line 69 of cpp/README.md from `cd graphar/cpp ` to `cd incubator-graphar/cpp`
Yes
No
=> docs: update README to correct wrong directory path for building cpp

README-zh-cn.md, README.md
fix #673 
modify README, remove meeting statements
no need
no
=> fix(doc): remove meeting statements in README.md

README.md
=> chore(doc): refine empty line

README.md
=> chore(doc): refine readme

.github/workflows/cli.yml
align Arrow version with the C++ CI environment and help avoid issues #720 caused by external dependency updates. 
cli.yml: set libarrow version 17.0.0-1
yes
no
=> fix(ci): align Arrow version in CLI with C++

.github/workflows/ci.yml, codecov.yml
=> feat(ci): focus cpp lcov code coverage reports to just core path

maven-projects/info/src/main/java/org/apache/graphar/info/AdjacentList.java, maven-projects/info/src/main/java/org/apache/graphar/info/EdgeInfo.java, maven-projects/info/src/main/java/org/apache/graphar/info/GraphInfo.java, maven-projects/info/src/main/java/org/apache/graphar/info/PropertyGroup.java, maven-projects/info/src/main/java/org/apache/graphar/info/VertexInfo.java, maven-projects/info/src/test/java/org/apache/graphar/info/AdjacentListTest.java, maven-projects/info/src/test/java/org/apache/graphar/info/EdgeInfoTest.java, maven-projects/info/src/test/java/org/apache/graphar/info/GraphInfoTest.java, maven-projects/info/src/test/java/org/apache/graphar/info/GraphInfoUriTest.java, maven-projects/info/src/test/java/org/apache/graphar/info/PropertyGroupTest.java, maven-projects/info/src/test/java/org/apache/graphar/info/VertexInfoTest.java
related #767 
1. add `isValidated` method
2. rename getxxxPrefix or getxxxPath to getxxxUri
3. add isValidated test case
4. fix srcType, edgeType, dstType order in `getEdgeInfo`
5. remove unused method
yes
no
=> feat(java,info): update validate and other methods
