apache/incubator-graphar

cmake/apache-arrow.cmake
The Github source tarball fails frequently from laptop.
The URL is taken from: https://arrow.apache.org/install/
=> Use the apache URL to download apache-arrow.

.github/workflows/ci.yml, CMakeLists.txt
Fixed #8 
Signed-off-by: acezen <qiaozi.zwb@alibaba-inc.com>
=> Add ccache to github actions

docs/api-reference.rst, include/gar/graph_info.h, include/gar/utils/convert_to_arrow_type.h, include/gar/utils/data_type.h, include/gar/utils/utils.h, include/gar/utils/version_parser.h, include/gar/writer/edges_builder.h, include/gar/writer/vertices_builder.h, src/arrow_chunk_writer.cc, src/data_type.cc, src/edges_builder.cc, src/graph.cc, src/graph_info.cc, src/utils.cc, src/version_parser.cc, src/version_paser.cc, src/vertices_builder.cc, test/test_example/test_bfs_father_example.cc, test/test_example/test_bfs_pull_example.cc, test/test_example/test_bfs_push_example.cc, test/test_example/test_bfs_stream_example.cc, test/test_example/test_bgl_example.cc, test/test_example/test_cc_push_example.cc, test/test_example/test_cc_stream_example.cc, test/test_example/test_construct_info_example.cc, test/test_example/test_pagerank_example.cc, test/test_info.cc
These changes are intend to support the feature that GraphAr Info can extend their supported data types base on their info version. Here we implement the feature by:
- Add a class `InfoVersion` to store the version information of info and provide function to parse version string.
- Modify the Info classes (VertexInfo, EdgeInfo, GraphInfo) constructor to support version attribute.
- Revise the `DataType` helper functions to adapt the version info. …
=> Add InfoVersion to store version information of info and support data type extension base on info version

docs/api-reference.rst, include/gar/graph.h, include/gar/utils/utils.h, src/graph.cc, src/utils.cc
The changes remove `include "arrow/api.h" from graph.h to avoid include any arrow header in GraphAr header files.
Fixed issue #49
=> Remove `include "arrow/api.h" from graph.h

requirements-dev.txt
The latest sphinx 0.6.0 is not compatible with docutils 0.16, remove `docutils` version limit to fix docs ci
- [] Documentation Update (if none of the other choices apply)
=> [Minor] Remove `docutils` version limit to fix docs ci

docs/index.rst, docs/user-guide/overview.rst, docs/user-guide/spark-tool.rst
Add introduction about GraphAr Spark tools in document.
Fixed issue: #24
=> Add introduction about GraphAr Spark tools in document 

spark/src/main/scala/com/alibaba/graphar/utils/FileSystem.scala, spark/src/main/scala/com/alibaba/graphar/writer/EdgeWriter.scala, spark/src/test/scala/com/alibaba/graphar/TestWriter.scala
This change aims to fix the offset chunk output path and offset value bugs of spark edge writer.
Fix issue #62
=> [BugFix][Spark] Fix offset chunk output path and offset value of spark writer

CMakeLists.txt
Required by: https://github.com/v6d-io/v6d/pull/1185
=> Address issues in handling yaml-cpp correctly when requires GraphAr in external projects

.gitleaks.toml, .pre-commit-config.yaml, CONTRIBUTING.rst
Enable `pre-commit` check for secrets.
=> Add pre-commit configuration and instructions

include/gar/graph.h, include/gar/utils/filesystem.h, include/gar/utils/reader_utils.h, src/filesystem.cc, src/reader_utils.cc
These changes add some auxiliary functions to get vertex chunk num or edge chunk num with vertex info, edge info and directory path to check.
if the directory not exist, it would raise an ArrowError
Fixed issues #90
=> [Improve] Add auxiliary functions to get vertex chunk num or edge chunk num with infos

.github/workflows/ci.yml, CMakeLists.txt, cmake/apache-arrow.cmake
=> [Improve] Use gar-related names for arrow project and ccache to avoid duplicated project name

CMakeLists.txt, cmake/apache-arrow.cmake
This pull request addresses two bugs:
- `include_directories(BEFORE SYSTEM ${ARROW_INCLUDE_DIR})` will bring `arrow_ep/include/...` to `gar`'s cmake dependency
- Without a private prefix for arrow definitions, there would be conflicts when the external projects both requires arrow and gar (using `add_subdirectory`).
=> Add prefix to arrow definitions to avoid conflicts

spark/src/main/scala/com/alibaba/graphar/reader/VertexReader.scala, spark/src/main/scala/com/alibaba/graphar/utils/FileSystem.scala, spark/src/main/scala/com/alibaba/graphar/writer/VertexWriter.scala, spark/src/test/scala/com/alibaba/graphar/TestWriter.scala
=> [BugFix][Spark] Fix the bug that VertexWrite does not generate vertex count file

docs/user-guide/spark-lib.rst, spark/src/main/scala/com/alibaba/graphar/EdgeInfo.scala, spark/src/main/scala/com/alibaba/graphar/GraphInfo.scala, spark/src/main/scala/com/alibaba/graphar/VertexInfo.scala, spark/src/main/scala/com/alibaba/graphar/reader/EdgeReader.scala, spark/src/main/scala/com/alibaba/graphar/reader/VertexReader.scala, spark/src/test/scala/com/alibaba/graphar/ComputeExample.scala, spark/src/test/scala/com/alibaba/graphar/TestGraphInfo.scala, spark/src/test/scala/com/alibaba/graphar/TestReader.scala, spark/src/test/scala/com/alibaba/graphar/TestWriter.scala, spark/src/test/scala/com/alibaba/graphar/TransformExample.scala
This change added helper objects and related methods in the GraphAr Spark library, for loading the info classes (GraphInfo, VertexInfo and EdgeInfo) from existing files.
solve issue #111
=> [Improvement][Spark] Add helper objects and methods for loading info classes from files

docs/user-guide/spark-lib.rst, spark/src/main/scala/com/alibaba/graphar/graph/GraphTransformer.scala, spark/src/test/scala/com/alibaba/graphar/TestGraphTransformer.scala
This change adds a GraphTransformer for the data transformation at the graph level. The methods can help the users to transform graphs through specifying yaml paths or GraphInfo objects of the two graphs.
related to issue #88
=> [Improvement][Spark] Provide APIs for data transformation at the graph level

docs/applications/spark.rst, docs/index.rst, docs/user-guide/spark-lib.rst, spark/pom.xml, spark/src/main/scala/com/alibaba/graphar/EdgeInfo.scala, spark/src/main/scala/com/alibaba/graphar/GraphInfo.scala, spark/src/main/scala/com/alibaba/graphar/VertexInfo.scala, spark/src/main/scala/com/alibaba/graphar/datasources/GarTable.scala, spark/src/main/scala/com/alibaba/graphar/writer/EdgeWriter.scala, spark/src/test/scala/com/alibaba/graphar/GraphAr2Neo4j.scala, spark/src/test/scala/com/alibaba/graphar/Neo4j2GraphAr.scala
This change add examples of migrating graph data between Neo4j and GraphAr as a key application of GraphAr. The examples are implemented based on the Neo4j Spark connector and the GraphAr Spark library, including reading graph data from Neo4j to generate GAR files, and reading from GraphAr to create/update instances in Neo4j.
related to issue #33 
add a new data type (Array) to Spark library, related to issue #76
=> [Examples][Spark] Add examples of integrating with the Neo4j spark connector as an application of GraphAr

.github/workflows/docs.yml, cpp/cmake/apache-arrow.cmake
We noticed some failure in vineyard in gar loader tests: https://github.com/v6d-io/v6d/actions/runs/4401800380/jobs/7708326106
Not sure why. But disabling jemalloc shouldn't be a big concern and it should be the easiest way for fixing the failure.
=> Disable jemalloc when building the bundled arrow

.gitignore, cpp/src/filesystem.cc
minor change: fix the warning when compiling GraphAr, such as:
```
In file included from /home/yee.yi/Workspace/GraphAr/cpp/include/gar/utils/filesystem.h:23,
from /home/yee.yi/Workspace/GraphAr/cpp/src/filesystem.cc:26:
/home/yee.yi/Workspace/GraphAr/cpp/src/filesystem.cc: In instantiation of ‘GraphArchive::Result<T> GraphArchive::FileSystem::ReadFileToValue(const string&) const [with T = long int; GraphArchive::Result<T> = cpp::
bitwizeshift::result<long int, GraphArchive::Status>; std::string = std::__cxx11::basic_string<char>]’:
/home/yee.yi/Workspace/GraphAr/cpp/src/filesystem.cc:271:31:   required from here
/home/yee.yi/Workspace/GraphAr/cpp/src/filesystem.cc:156:45: warning: unused variable ‘bytes’ [-Wunused-variable]
156 |   GAR_RETURN_ON_ARROW_ERROR_AND_ASSIGN(auto bytes,
| …
```
=> [Minor][C++] Fix compile warning

README.rst, spark/README.rst
GraphAr would use Discord as our community tool for developer and users. Add GraphAr discord server invite link and banner to README. 
=> [Minor] Add discord invite link and banner to README

cpp/include/gar/graph.h, cpp/test/test_graph.cc
This change implements the add operator for VertexIter, for random access of vertices in a collection.
related to issue #78
=> [Improvement][C++] Implement the add operator for VertexIter

cpp/CMakeLists.txt, cpp/cmake/apache-arrow.cmake
- Adjust the arrow version to 10.0.1 to adapt the most frequently used arrow version in MacOS and vineyard.
- include the bundle arrow header when building test and example to avoid conflict arrow version between system and GraphAr
=> [Minor][C++] Adjust the dependency version of arrow and fix arrow header conflict bug 

cpp/include/gar/graph.h, cpp/include/gar/utils/reader_utils.h, cpp/src/graph.cc, cpp/src/reader_utils.cc, cpp/test/test_graph.cc
This PR improves the usability of EdgesCollection by: 
- support to construct the EdgesCollection for a range of vertex chunks
- support to get the number of edges in a EdgesCollection
related to issue #130 & issue #78
=> [Improvement][C++] Improve the usability of EdgesCollection

cpp/include/gar/reader/arrow_chunk_reader.h, cpp/include/gar/reader/chunk_info_reader.h
When a vertex chunk has no edge, the next_chunk() function of readers for adj_list/adj_list_property may get errors since it reads a non-existing chunk.
=> [BugFix][C++] Fix next_chunk() of readers in the C++ library

cpp/include/gar/utils/data_type.h, cpp/include/gar/writer/arrow_chunk_writer.h, cpp/src/arrow_chunk_writer.cc, cpp/test/test_arrow_chunk_writer.cc
This update includes the implementation of various validation levels in the GraphAr C++ SDK writers. These new validation levels could ensure the consistency of data types between the data and meta info before being written.
related to issue #127
=> [Improvement][C++] Add validation for data types for writers in C++ library

cpp/examples/bfs_father_example.cc, cpp/include/gar/graph.h, cpp/include/gar/graph_info.h, cpp/include/gar/reader/arrow_chunk_reader.h, cpp/include/gar/reader/chunk_info_reader.h, cpp/include/gar/utils/reader_utils.h, cpp/include/gar/writer/arrow_chunk_writer.h, cpp/include/gar/writer/edges_builder.h, cpp/src/arrow_chunk_writer.cc, cpp/src/reader_utils.cc, cpp/test/test_arrow_chunk_writer.cc, cpp/test/test_info.cc, docs/user-guide/getting-started.rst
This PR introduces the vertex_count file to record the number of vertices for storing edges in GraphAr: number of source vertices for ordered_by_source/unordered_by_source edges; number of destination vertices for ordered_by_dest/unordered_by_dest edges.
related to issue #126
=> [C++] Add vertex_count file for storing edges in GraphAr

.github/workflows/ci.yml, cpp/cmake/apache-arrow.cmake
The Arrow of GraphAr is building with `ARROW_OPENSSL_USE_SHARED=OFF` by default. BUT centos yum installed openssl only provide shared library, that would get `Not Found OpenSSL::SSL` error when building arrow.
this change set `ARROW_OPENSSL_USE_SHARED=ON` in arrow building configuration and add a centos8 ci to verify Graphar building process on centos.
=> Fix building arrow bug on centos8

cpp/include/gar/graph.h, cpp/test/test_graph.cc
PR #128 implements the add operator for VertexIter for random accessing for VerticesCollection. This change implements the add-assign operator for VertexIter which modifies it in-place to avoid copy all readers in the VertexIter.
related to issue #78
=> [Improvement][C++] Implement the add-assign operator for VertexIter

README.rst, cpp/README.rst, docs/user-guide/getting-started.rst, docs/user-guide/spark-lib.rst, spark/README.rst
=> [Doc] Refine building steps to be more clear in ReadMe

cpp/include/gar/writer/arrow_chunk_writer.h
=> [BugFix] Fix compile error on ARM platform

cpp/include/gar/graph.h, cpp/test/test_graph.cc
This change supports to get reference of a property in Vertex/Edge, avoiding copy the value.
related to #78
=> [C++] [Improvement] Support to get reference of property in Vertex/Edge

cpp/cmake/apache-arrow.cmake, cpp/src/arrow_chunk_writer.cc
Signed-off-by: acezen <qiaozi.zwb@alibaba-inc.com>
Committed-by: acezen from Dev container
Address issue #161 
Fixed #161
=> [C++] Align arrow version to system if arrow installed

.github/workflows/ci.yml, cpp/CMakeLists.txt, cpp/cmake/apache-arrow.cmake
Signed-off-by: acezen <qiaozi.zwb@alibaba-inc.com>
Committed-by: acezen from Dev container
Since arrow 12.0.0 has move `ExecPlan` from `compute` to `acero`, and new a `libarrow_acero.a`. This change make libgar to link arrow acero static library when building with arrow 12.0.0 or greater.
Fixed #163
=> [C++][BugFix] Fix the arrow acero not found error when building with arrow 12.0.0 or greater

cpp/CMakeLists.txt, cpp/examples/bfs_father_example.cc, cpp/examples/bfs_pull_example.cc, cpp/examples/bfs_push_example.cc, cpp/examples/bfs_stream_example.cc, cpp/examples/bgl_example.cc, cpp/examples/cc_push_example.cc, cpp/examples/cc_stream_example.cc, cpp/examples/config.h, cpp/examples/construct_info_example.cc, cpp/examples/pagerank_example.cc
=> [BugFix] [C++] Make examples to generate result files under build type of release

cpp/include/gar/writer/edges_builder.h, cpp/include/gar/writer/vertices_builder.h, cpp/src/edges_builder.cc, cpp/src/vertices_builder.cc, cpp/test/test_builder.cc
Similar to the GraphAr C++ SDK writers, we could add the implementation of various validation levels in the builders (`VerticesBuilder` &` EdgesBuilder`).  A strong validation level could ensure the consistency of data types between the data and meta info before being written.
solve issue #171
=> [C++][Improvement] Add validation of different levels for builders in C++ library

cpp/README.rst, spark/README.rst
Refine build command in README in cpp.
=> [Doc]Refine README in cpp about building

cpp/include/gar/utils/writer_utils.h, cpp/include/gar/writer/arrow_chunk_writer.h, cpp/include/gar/writer/edges_builder.h, cpp/include/gar/writer/vertices_builder.h, cpp/src/arrow_chunk_writer.cc, cpp/src/edges_builder.cc, cpp/src/vertices_builder.cc, cpp/test/test_arrow_chunk_writer.cc, cpp/test/test_builder.cc, docs/reference/api-reference-cpp.rst
We need to develop a more comprehensive and consistent approach to validation across all of GraphAr's tools and libraries. As the first step, this change redesigned and unified the implementation of validation for `Writer` and `Builder` in the C++ library.
- clarify and define different validation levels in the utils
- hide the `Validate` interface to users and use `validate_level` as a parameter of the writing operations
- simplify and unify the implementation for validation in `Writer` and `Builder`
- add a `Clear()` method to high-level `Builder`, enabling to add data and then dump for multiple rounds
- add test to prove the interface changes
- update C++ API Reference to include the `ValidateLevel` type
_Put an `x` in the …
=> [C++][Improvement] Redesign and unify the implementation of validation in C++ Writer/Builder

.github/workflows/docs.yml
See also https://github.com/alibaba/GraphScope/pull/2941 and https://github.com/alibaba/GraphScope/pull/2943.
=> Fixes the pull_request_target usage to avoid the secret leak issue.

cpp/include/gar/graph.h, cpp/include/gar/graph_info.h, cpp/include/gar/reader/arrow_chunk_reader.h, cpp/include/gar/reader/chunk_info_reader.h, cpp/include/gar/utils/status.h, cpp/include/gar/writer/edges_builder.h, cpp/include/gar/writer/vertices_builder.h, cpp/src/arrow_chunk_reader.cc, cpp/src/arrow_chunk_writer.cc, cpp/src/chunk_info_reader.cc, cpp/src/edges_builder.cc, cpp/src/filesystem.cc, cpp/src/graph.cc, cpp/src/graph_info.cc, cpp/src/reader_utils.cc, cpp/src/utils.cc, cpp/src/version_parser.cc, cpp/src/vertices_builder.cc, cpp/test/test_arrow_chunk_reader.cc, cpp/test/test_arrow_chunk_writer.cc, cpp/test/test_builder.cc, cpp/test/test_chunk_info_reader.cc, cpp/test/test_info.cc
This change aims to refine the error constructor and fulfill the error message detail for C++ SDK.
- Refine the error constructor with [parameter pack](https://en.cppreference.com/w/cpp/language/parameter_pack), so developers can construct the error by only passing the messages to constructor, no need to concatenate as a string.
- Fulfill the detail message of error in C++ SDK to let user/developer know what the error is about and why it turn out.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your …
=> [Improvement][C++] Refine the error message of errors of C++ SDK

spark/src/main/scala/com/alibaba/graphar/EdgeInfo.scala, spark/src/main/scala/com/alibaba/graphar/GraphInfo.scala, spark/src/main/scala/com/alibaba/graphar/VertexInfo.scala
Current spark generated info yaml can't not be load by C++ SDK, Set the format options to adapt the format to BLOCK which is the format like https://github.com/GraphScope/gar-test/tree/d8dd7fd931a3893f81fa236b7be20952667ac716/ldbc
=> [Minor][Spark] Adapt spark yaml format to BLOCK

cpp/include/gar/external/result.hpp, cpp/include/gar/graph_info.h, cpp/test/test_builder.cc
current when access value fail with `Result`, it just output message like:
`error attempting to access value from result containing error`.
This change change the behavior that output the message of error it contain.
Fixed issue: #218
=> [Feat][C++] Output the error message when access value in Result fail

spark/src/main/scala/com/alibaba/graphar/datasources/GarScan.scala, spark/src/main/scala/com/alibaba/graphar/datasources/GarScanBuilder.scala, spark/src/main/scala/com/alibaba/graphar/datasources/GarTable.scala, spark/src/main/scala/com/alibaba/graphar/reader/VertexReader.scala, spark/src/test/scala/com/alibaba/graphar/TestReader.scala
This PR is about C++ SDK for [OSPP 2023](https://summer-ospp.ac.cn/org/prodetail/2313e0400?list=org&navpage=org)
Issue number: https://github.com/alibaba/GraphAr/issues/98. 
You can find more detail about this feature [here](https://docs.google.com/document/d/1S6zlBrzTlk515ALWWWaMNJGN2lTo5ZPygPNRCaZHAWw/edit?usp=sharing)
Now we support filter pushdown for spark
=> [Spark] Support property filter pushdown by utilizing payload file formats

.github/workflows/spark.yaml, spark/README.md, spark/pom.xml, spark/scripts/deploy-nebula-default-data.sh, spark/scripts/get-nebula-to-home.sh, spark/scripts/run-graphar2nebula.sh, spark/scripts/run-nebula2graphar.sh, spark/src/main/scala/com/alibaba/graphar/example/GraphAr2Nebula.scala, spark/src/main/scala/com/alibaba/graphar/example/Nebula2GraphAr.scala
close #34
example in gar-test: https://github.com/GraphScope/gar-test/pull/4
=> [Feat][Spark] Add examples to show how to load/dump data from/to GraphAr for Nebula

cpp/examples/high_level_reader_example.cc, cpp/examples/high_level_writer_example.cc, cpp/examples/low_level_reader_example.cc, cpp/examples/mid_level_reader_example.cc, cpp/examples/mid_level_writer_example.cc
This change adds examples of using C++ reader/writer.
solve #205
=> [C++] Add examples about how to use C++ reader/writer

docs/applications/spark.rst, docs/user-guide/spark-lib.rst, spark/src/main/scala/com/alibaba/graphar/example/GraphAr2Nebula.scala, spark/src/main/scala/com/alibaba/graphar/example/GraphAr2Neo4j.scala, spark/src/main/scala/com/alibaba/graphar/graph/GraphReader.scala, spark/src/main/scala/com/alibaba/graphar/graph/GraphWriter.scala, spark/src/main/scala/com/alibaba/graphar/util/DataFrameConcat.scala, spark/src/main/scala/com/alibaba/graphar/util/FileSystem.scala, spark/src/main/scala/com/alibaba/graphar/writer/EdgeWriter.scala, spark/src/main/scala/com/alibaba/graphar/writer/VertexWriter.scala, spark/src/test/scala/com/alibaba/graphar/ComputeExample.scala, spark/src/test/scala/com/alibaba/graphar/TestWriter.scala
=> [Doc][Spark] Update the doc: fix the outdated argument annotations and typo

.github/workflows/java.yml, docs/Makefile, java/src/main/java/com/alibaba/graphar/edges/EdgesCollection.java, java/src/main/java/com/alibaba/graphar/vertices/VerticesCollection.java, java/src/test/java/com/alibaba/graphar/edges/EdgesCollectionTest.java, java/src/test/java/com/alibaba/graphar/vertices/VerticesCollectionTest.java
=> [Improve][Java] Make EdgesCollection and VerticesCollection support foreach loop

.github/workflows/ci.yml, .github/workflows/java.yml
=> [Minor][CI] Install certain version of arrow in CI to avoid breaking down CI when arrow upgrade

spark/src/main/scala/com/alibaba/graphar/EdgeInfo.scala, spark/src/main/scala/com/alibaba/graphar/GraphInfo.scala, spark/src/main/scala/com/alibaba/graphar/VertexInfo.scala, spark/src/main/scala/com/alibaba/graphar/datasources/GarScan.scala, spark/src/main/scala/com/alibaba/graphar/datasources/GarScanBuilder.scala, spark/src/main/scala/com/alibaba/graphar/datasources/GarTable.scala, spark/src/main/scala/com/alibaba/graphar/graph/GraphTransformer.scala, spark/src/main/scala/com/alibaba/graphar/graph/GraphWriter.scala, spark/src/main/scala/com/alibaba/graphar/reader/EdgeReader.scala, spark/src/main/scala/com/alibaba/graphar/reader/VertexReader.scala, spark/src/main/scala/com/alibaba/graphar/writer/EdgeWriter.scala, spark/src/main/scala/com/alibaba/graphar/writer/VertexWriter.scala
Complement the error messages of spark, throw exception with error message.
close #140
=> [Improvement][Spark] Complement the error messages of spark SDK

cpp/include/gar/fwd.h, cpp/include/gar/graph.h, cpp/include/gar/util/convert_to_arrow_type.h, cpp/include/gar/util/data_type.h, cpp/include/gar/util/util.h, cpp/include/gar/writer/edges_builder.h, cpp/include/gar/writer/vertices_builder.h, cpp/src/data_type.cc, cpp/src/edges_builder.cc, cpp/src/graph.cc, cpp/src/graph_info.cc, cpp/src/vertices_builder.cc, cpp/test/test_graph.cc, docs/file-format.rst, spark/src/main/scala/com/alibaba/graphar/GraphInfo.scala
This pull request aims to support `List` data type in GraphAr C++ and add related unit-test
- Support `List` data type by add a `child_` to `DataType` class, implement by nested other logical data type.
- In high level reader, support read list property  in `Vertex`/`Edge`.
yaml example:
```bash
property:
- name: feature
- data_type: list<float>
- is_primary: false
```
NB: since BooleanArray and StringArray'method are not align to NumericalArray, so we only support `list<int32>` `list<int64>`, `list<float>` and `list<double>` at present.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here …
=> [Feat][C++] Support List Data Type, use `list<float>` as example

spark/src/main/scala/com/alibaba/graphar/GraphInfo.scala, spark/src/test/scala/com/alibaba/graphar/TestGraphInfo.scala
This change add `override equals` to `Property`, `PropertyGroup` and `AdjList` to fix the comparison behavior.
closed issue: #303
=> [BugFix][Spark] Fix the comparison behavior of Property/PropertyGroup/AdjList

spark/README.md
Fix the url to spark lib's getting started.
=> [Minor][Doc] Fix spark url in README.md

pyspark/graphar_pyspark/info.py, pyspark/tests/test_info.py, pyspark/tests/test_reader.py, pyspark/tests/test_transform.py, pyspark/tests/test_writer.py, spark/src/main/scala/com/alibaba/graphar/EdgeInfo.scala, spark/src/main/scala/com/alibaba/graphar/GraphInfo.scala, spark/src/main/scala/com/alibaba/graphar/reader/EdgeReader.scala, spark/src/main/scala/com/alibaba/graphar/util/Utils.scala, spark/src/main/scala/com/alibaba/graphar/writer/EdgeWriter.scala, spark/src/test/scala/com/alibaba/graphar/ComputeExample.scala, spark/src/test/scala/com/alibaba/graphar/TestGraphInfo.scala, spark/src/test/scala/com/alibaba/graphar/TestGraphReader.scala, spark/src/test/scala/com/alibaba/graphar/TestGraphTransformer.scala, spark/src/test/scala/com/alibaba/graphar/TestReader.scala, spark/src/test/scala/com/alibaba/graphar/TestWriter.scala, spark/src/test/scala/com/alibaba/graphar/TransformExample.scala
Update the graphar-spark implementation of EdgeInfo to the latest design that extract property group from adj list.
sync the update to graphar-pyspark too.
the edge info  from
```
src_label: person
edge_label: created
dst_label: software
chunk_size: 2
src_chunk_size: 2
dst_chunk_size: 10
directed: true
prefix: edge/person_created_software/
adj_lists:
- ordered: true
aligned_by: src
prefix: ordered_by_source/
file_type: csv
property_groups:
- prefix: weight/
file_type: csv
properties:
- name: weight
data_type: double
is_primary: false
```
change to
```
src_label: person
edge_label: created
dst_label: software
chunk_size: 2
src_chunk_size: 2
dst_chunk_size: 10
directed: true
prefix: edge/person_created_software/
adj_lists:
- ordered: true
aligned_by: src
prefix: ordered_by_source/ …
```
=> [Feat][Spark] Align info implementation of spark with c++

spark/src/main/java/com/alibaba/graphar/GeneralParams.java, spark/src/main/scala/com/alibaba/graphar/graph/GraphTransformer.scala, spark/src/main/scala/com/alibaba/graphar/graph/GraphWriter.scala, spark/src/main/scala/com/alibaba/graphar/util/FileSystem.scala, spark/src/main/scala/com/alibaba/graphar/writer/EdgeWriter.scala, spark/src/main/scala/com/alibaba/graphar/writer/VertexWriter.scala
This change tuning the memory usage of GraphAr spark with
- Persist the DataFrame and RDD that frequently used and unpersist them when they are not used anymore.
- Use `MEMORY_AND_DISK_SER` as persist storage level for reduce the memory usage
related #324 
close #322
=> [Feat][Spark] Memory tuning for GraphAr spark with persist and storage level

spark/src/main/scala/com/alibaba/graphar/writer/EdgeWriter.scala
This change convert the sequence process of offset chunks to parallel
close #328
=> [Improvement][Spark] Improve the writer effeciency with parallel process

docs/cpp/getting-started.rst
=> [Minor][Spark] minor doc fix

cpp/benchmarks/benchmark_util.h, cpp/examples/config.h, cpp/test/util.h, java/src/test/java/com/alibaba/graphar/graphinfo/GraphInfoTest.java, pyspark/tests/test_transform.py, spark/src/test/scala/com/alibaba/graphar/ComputeExample.scala, spark/src/test/scala/com/alibaba/graphar/TestGraphInfo.scala, spark/src/test/scala/com/alibaba/graphar/TestGraphReader.scala, spark/src/test/scala/com/alibaba/graphar/TestGraphTransformer.scala, spark/src/test/scala/com/alibaba/graphar/TestReader.scala, spark/src/test/scala/com/alibaba/graphar/TestWriter.scala, spark/src/test/scala/com/alibaba/graphar/TransformExample.scala
=> [BugFix][C++] Update the testing path with latest testing repo

README.rst
Enhance the ReadMe with additional information about the GraphAr libraries
=> [Doc] Enhance the ReadMe with additional information about the GraphAr libraries

spark/src/main/scala/com/alibaba/graphar/example/Neo4j2GraphAr.scala
=> [Improvement][Spark] Try to make neo4j generate DataFrame with the correct data type

cpp/.gitignore, cpp/include/gar/graph_info.h, cpp/src/graph_info.cc, cpp/test/test_info.cc, docs/file-format.rst
When property is not primary key and the `is_nullable` field is not exist, it well be set as nullable by default.
When property is primary, the `is_nullable` field will be ignored.
Progress:
Related issue #351
=> [Feat][Format][C++] Support nullable key for property in meta-data

cpp/include/gar/fwd.h, cpp/include/gar/graph_info.h, cpp/src/graph_info.cc, cpp/test/test_info.cc, docs/file-format.rst
This pull request aims to add a `extra_info` field to graph info that provides ability for user to write and read user-defined metadata.
related to #354
=> [Feat][Format][C++] Support extra info in graph info

cpp/include/gar/graph.h, cpp/include/gar/reader/arrow_chunk_reader.h, cpp/src/arrow_chunk_reader.cc, cpp/test/test_arrow_chunk_reader.cc
=> [Improve][C++] Revise the ArrowChunkReader constructors by remove redundant parameter

spark/graphar/src/main/scala/com/alibaba/graphar/EdgeInfo.scala, spark/graphar/src/main/scala/com/alibaba/graphar/GraphInfo.scala, spark/graphar/src/main/scala/com/alibaba/graphar/VertexInfo.scala, spark/graphar/src/test/scala/com/alibaba/graphar/TestGraphInfo.scala
source code was done. Besides, should update test data with `is_nullable` declared directly.
related issue #351
=> [Feat][Format][Spark] Add nullable key in meta-data

pyspark/graphar_pyspark/info.py, pyspark/tests/test_info.py
Update PySpark implementation following GraphAr Spark updates.
Close #372 
.
=> [Feat][Spark] Update PySpark bindings following GraphAr Spark

cpp/examples/snap_dataset_to_graphar.cc, docs/cpp/examples/index.rst, docs/cpp/examples/snap-to-graphar.rst
This PR provides a sample conversion of [SNAP](https://snap.stanford.edu/index.html) datasets into GraphAr format, showcasing the process with the Facebook graph as a case study. The conversion leverages GraphInfo constructors and the high-level writer functions from the C++ library.
As part of #275
=> [C++] Include an example of converting SNAP datasets to GraphAr format

cpp/include/gar/graph_info.h, cpp/src/graph_info.cc
Fixes several compilation warnings in C++ SDK.
=> [Improvement][C++] Fixes compilation warnings in C++ SDK

cpp/src/data_type.cc
=> [Minor][C++] Revise the unsupported data type error msg to give more information

cpp/include/gar/graph_info.h, cpp/src/graph_info.cc, cpp/test/test_info.cc
This change aims to fix that PropertyGroup with empty properties bug
- Not allow create property group with empty properties, if so, it's invalid;
- Not allow create edge info with empty adj list vector, if so, it's invalid;
- Not allow empty label name and chunk_size <= when create VertexInfo/EdgeInfo
- Add `try..  catch..` to catch exception in `Dump` methods. 
close #392
=> [BugFix][C++] Fix bug: PropertyGroup with empty properties make VertexInfo/EdgeInfo dumps failed

cpp/src/graph_info.cc, cpp/test/test_info.cc
Fix `VertexInfo/EdgeInfo` can not save to a URI path.
close #394
=> [BugFix][C++]: Fix `VertexInfo/EdgeInfo` can not be saved to a URI path

.github/workflows/spark.yaml, pyspark/Makefile
As described in #404 
I cannot see dramatic changes in performance (spark 3.3, spark 3.2), but I can guess that in the future versions of spark more and more things will be disabled/simplified when it is turned on. On spark 3.4/3.5 performance improvement should be significant.
=> [Minor][Spark] Add SPARK_TESTING variable to increse tests performance

spark/graphar/src/main/java/com/alibaba/graphar/info/EdgeInfo.java, spark/graphar/src/main/java/com/alibaba/graphar/info/PropertyGroup.java, spark/graphar/src/main/java/com/alibaba/graphar/info/VertexInfo.java, spark/graphar/src/main/java/com/alibaba/graphar/info/yaml/EdgeYamlParser.java
Here I created a class called `PropertyGroups` for conveiently used by vertex info and edge info, it shouldn't be exposed to out side.
related issue #406
=> [Spark][Java][Info] Add property-group-related methods for edge info and vertex info

cpp/CMakeLists.txt, cpp/README.md, cpp/examples/high_level_writer_example.cc, cpp/include/gar/fwd.h, cpp/include/gar/util/macros.h, cpp/test/test_builder.cc, docs/cpp/examples/bgl.rst, docs/cpp/examples/out-of-core.rst, docs/cpp/getting-started.rst, docs/cpp/reference/index.rst
as #412 describe
close issue #412
=> [FEAT][C++] Change the default namespace to `graphar`

.github/workflows/docs.yml, .github/workflows/pyspark.yml
Apache project only allows to use github or apache's actions, try to replace the third-party action in CI.
=> [Infra] Remove the third party action from CI

cpp/benchmarks/benchmark_util.h, cpp/examples/config.h, cpp/include/gar/api.h, cpp/include/gar/fwd.h, cpp/include/gar/graph.h, cpp/include/gar/graph_info.h, cpp/include/gar/reader/arrow_chunk_reader.h, cpp/include/gar/reader/chunk_info_reader.h, cpp/include/gar/util/adj_list_type.h, cpp/include/gar/util/convert_to_arrow_type.h, cpp/include/gar/util/data_type.h, cpp/include/gar/util/expression.h, cpp/include/gar/util/file_type.h, cpp/include/gar/util/filesystem.h, cpp/include/gar/util/general_params.h, cpp/include/gar/util/macros.h, cpp/include/gar/util/reader_util.h, cpp/include/gar/util/result.h, cpp/include/gar/util/status.h, cpp/include/gar/util/util.h, cpp/include/gar/util/version_parser.h, cpp/include/gar/util/writer_util.h, cpp/include/gar/util/yaml.h, cpp/include/gar/writer/arrow_chunk_writer.h, cpp/include/gar/writer/edges_builder.h, cpp/include/gar/writer/vertices_builder.h, cpp/test/util.h
This change use `#pragma once` to replace `#ifndef` as  include guards
Fixs #454
=> [FEAT][C++] Use `#pragma once` to replace `#ifndef` as  include guards

cpp/include/gar/reader/arrow_chunk_reader.h, cpp/src/arrow_chunk_reader.cc, cpp/src/filesystem.cc, cpp/test/test_arrow_chunk_reader.cc
as issue #219 describe, the chunk table get from arrow chunk reader may not has the same type with schema.
This change help to fix the problem by cast the chunk table to what they should be(schema), if cast failed, raise error.
fixes #219
=> [BugFix][C++] Cast to correct schema when get chunk with property reader

NOTICE, cpp/CMakeLists.txt, cpp/src/filesystem.cc, cpp/thirdparty/simple-uri-parser/uri_parser.h, licenses/LICENSE-simple-uri-parser
=> feat(c++):  Use simple-uri-parser as uri parser, remove the rely on arrow::internal::URI

cpp/README.md, docs/libraries/java/java.md, docs/libraries/pyspark/pyspark.md, docs/libraries/spark/spark.md, java/README.md, spark/README.md
=> chore: Update directory paths in README files

maven-projects/pom.xml
https://maven.apache.org/pom/asf/
Apache Software Foundation Parent POM
contains settings that are likely to be useful to any Apache project that is building and releasing code with Maven. By using this project as a parent, a project gets these settings.
**If we have specific version requirements for certain plugins, we need to explicitly declare the corresponding versions in the project. Otherwise, it will default to the version specified in the parent POM.**
- Add mailing list and License etc
=> feat(java): Set parent pom to apache

LICENSE, NOTICE, maven-projects/java/build.xml, maven-projects/java/src/main/java/org/apache/graphar/stdcxx/StdMap.java, maven-projects/java/src/main/java/org/apache/graphar/stdcxx/StdSharedPtr.java, maven-projects/java/src/main/java/org/apache/graphar/stdcxx/StdString.java, maven-projects/java/src/main/java/org/apache/graphar/stdcxx/StdUnorderedMap.java, maven-projects/java/src/main/java/org/apache/graphar/stdcxx/StdVector.java
as apache [legal discussion](https://issues.apache.org/jira/browse/LEGAL-626) describe, if the code is modified on top of the reference code, we can also add the corresponding AL2 header.
add the corresponding AL2 header to reference code if modified on top of it.
no need to test
no
=> fix(license): add reference code to java related third-party code

cpp/README.md, cpp/test/test_arrow_chunk_reader.cc, cpp/test/test_arrow_chunk_writer.cc, cpp/test/test_builder.cc, cpp/test/test_chunk_info_reader.cc, cpp/test/test_graph.cc, cpp/test/util.h
Update the method to get testing dir with filesystem for convenient to build and test
Update the method to get testing dir:
use filesystem, deprecated environment variable GAR_TEST_DATA
already test with current unit tests
no
=> feat(c++): get testing data dir with filesystem relative path in unit tests

cpp/CMakeLists.txt
Fix the cmake warning of building process
=> fix(c++): Fix cmake warning

cpp/benchmarks/arrow_chunk_reader_benchmark.cc, cpp/examples/high_level_reader_example.cc
as title
Fix the warning of debug buidling
yes
no
=> fix(c++): Fix debug building warning

CHANGELOG.md
Add CHANGELOG.md to project to to document all changes made to the project.
- Add CHANGELOG.md
- add changes of v0.1.0 to v0.11.4 to CHANGELOG.md
=> chore: Add CHANGELOG.md

maven-projects/spark/graphar/src/main/scala/org/apache/graphar/example/LdbcSample2GraphAr.scala, maven-projects/spark/graphar/src/main/scala/org/apache/graphar/util/Utils.scala, maven-projects/spark/scripts/run-ldbc-sample2graphar.sh
#527 describe
- The specified schema make the `knows_edge_df` got many wrong null value, use `inferSchema` to make the read operation to get a correct dataframe.
- Since this is example, use `csv` as payload file output make more sense.
yes 
no
=> fix(spark): Fix the LdbcSample2GraphAr result and use csv as output

.github/workflows/ci.yml
Deprecate the centos CI since the centos:7 image is too old and the `actions/checkout@v3` can not work on it:
```bash
/usr/bin/docker exec  7c554302d7825ddb6842d137e48460adb118f64955dbfb6e1557261385995898 sh -c "cat /etc/*release | grep ^ID"
/__e/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node) …
```
=> fix(ci): deprecate centos ci in cpp action

cpp/src/graphar/arrow/chunk_reader.cc, cpp/src/graphar/arrow/chunk_reader.h, cpp/test/test_arrow_chunk_reader.cc
as #549 describe, when there are no edge of a vertex chunk, the directory could be empty, and the GetChunk would return `IOError`. 
Instead of return IOError, change to return a nullptr since the GetChunk operation should be OK and just the return chunk is empty.
the test case will be added.
No
=> fix(c++): return nullptr at GetChunk if there is no edge in chunk

cpp/CMakeLists.txt
Since brew installed arrow does not include orc extension. This PR add a fix to raise fatal message to terminate the build process if it does not find the orc extension.
Fix issues #547 and #545 
a testing item added in CMakeList.
Yes. but the test case is not included in PR, since it only affects a building failed codepath.
No.
=> fix(c++): Raise error if cmake found arrow built without ORC support.

docs/overview/overview.md, docs/specification/format.md
Fix an image cannot display bug when open docs from README docs. 
Currently, the images in the docs are given the relative URL, which will lead to a cannot display bug:
Since clicking from github README, the link will automatically appending a '/', e.g., 
clicking on https://graphar.apache.org/docs/specification/format, 
it actually open the URL https://graphar.apache.org/docs/specification/format/
The endling '/' affected the relative path, (by add an extra level), leading the images cannot by found and return a 404 error. 
Using absolute path can solve this problem.
Better still, even the [docs in github repo kept correctly displayed](https://github.com/yecol/incubator-graphar/blob/docs/docs/specification/format.md).
=> docs: change images in docs from relative url to absolute url.

CONTRIBUTING.md, README.md, docs/libraries/cpp/examples/bgl.md, docs/libraries/cpp/examples/snap-to-graphar.md, docs/libraries/cpp/getting-started.md
Currently the docs pages do not display code syntax highlight correctly. 
e.g., https://graphar.apache.org/docs/libraries/cpp/examples/bgl
This PR fix a bug and show the syntax like this:
- code hint: c++ -> cpp
Yes.
No.
=> docs: fix a bug prevented highlighting code syntax correctly.

.github/workflows/ci.yml, README.md
solution to https://github.com/apache/incubator-graphar/issues/189
Add test coverage to CI to measure the covering code of unitest and add banner to README 
yes
only README
=> feat(devinfra): Add test coverage to CI to measure the covering code of unit test and add banner to README (C++)

.github/workflows/spark.yaml, maven-projects/spark/pom.xml
solution to https://github.com/apache/incubator-graphar/issues/189, extension of https://github.com/apache/incubator-graphar/pull/580
Add Spark test coverage to CI to measure the covering code of unitest### Are these changes tested?
no
=> feat(devinfra): Add  test coverage to CI to measure the covering code of unitest (Spark)

maven-projects/spark/graphar/src/main/scala/org/apache/graphar/util/Utils.scala
Since the `redact` has been copy to datasource, the code in Utils can be removed
remove the `redact` code from Utils
yes
no
=> chore(spark): remove `Utils.redact`

dev/release/setup-ubuntu.sh
`C++` now rely on protobuf dependencies https://github.com/apache/incubator-graphar/blob/359b82960b368e3780dfda461b8bc984610e8cca/cpp/CMakeLists.txt#L210
add libprotobuf-dev in setup-ubuntu.sh
yes
no
=> fix(dev): add libprotobuf-dev in setup-ubuntu.sh

.github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/format.yml, .github/workflows/java.yml, .github/workflows/spark.yaml
as #602 describe
Add check that avoid running CI if PR is still working in progress
yes
no
=> feat(ci): avoid running CI if pull request is still working in progress

format/edge_info.proto, format/graph_info.proto, format/vertex_info.proto
add  segment to  protobuf definiton
yes
no
=> feat(format): add  segment for info in protobuf definiton

.github/workflows/ci-nightly.yml, cpp/CMakeLists.txt, cpp/README.md, cpp/cmake/apache-arrow.cmake, cpp/src/graphar/filesystem.cc
There may be senerio that user want to build graphar as a whole static library that include all the dependencies. arrow's static distribution does not include some libraries like thrift, aws...
So we may build arrow from the source.
- recover the `BUILD_ARROW_FROM_SOURCE` to support build arrow from source and link graphar as a single static library that includes all the dependencies.
- add a nightly ci to check the option.
yes
no
=> feat(c++): recover the BUILD_ARROW_FROM_SOURCE option

maven-projects/spark/graphar/src/main/scala/org/apache/graphar/graph/GraphWriter.scala, maven-projects/spark/graphar/src/main/scala/org/apache/graphar/writer/EdgeWriter.scala, maven-projects/spark/graphar/src/main/scala/org/apache/graphar/writer/VertexWriter.scala
=> chore(spark): fix typo in writer

cpp/CMakeLists.txt, cpp/src/graphar/arrow/chunk_reader.cc, cpp/src/graphar/arrow/chunk_reader.h, cpp/src/graphar/arrow/chunk_writer.cc, cpp/src/graphar/arrow/chunk_writer.h, cpp/src/graphar/filesystem.cc, cpp/src/graphar/filesystem.h, cpp/src/graphar/general_params.h, cpp/test/test_multi_label.cc
add function for support label related fuction.
chunk_reader, chunk_writer and test cases.
yes
=> feat(c++): add function and example for read and write label chunk

cpp/CMakeLists.txt, cpp/benchmarks/benchmark_util.h, cpp/benchmarks/label_filter_benchmark.cc, cpp/examples/label_filtering_example.cc, cpp/src/graphar/high-level/graph_reader.cc, cpp/src/graphar/high-level/graph_reader.h, cpp/src/graphar/label.cc, cpp/src/graphar/label.h
Provides API for label filtering
New features about label--filtering vertices with specific labels
yes, and efficiency are shown in bechmark, correctness are shown in example
yes, feature as above
=> feat(c++): label filtering API, benchmarks, and examples

cpp/src/graphar/fwd.h
=> chore(c++): update fwd.h to add label parameter

maven-projects/info/pom.xml, maven-projects/info/src/main/java/org/apache/graphar/info/loader/LocalYamlGraphLoader.java, maven-projects/info/src/main/java/org/apache/graphar/info/saver/LocalYamlGraphSaver.java
Close #664 
- Removing of Hadoop dependencies
- Corresponding updates of LocalGrapheSaver/Loader
All the existing tests are passed.
No. GraphAr-Info is not used at the moment, the package is under active development.
=> feat(java): remove Hadoop dependency and update tests / Local

.asf.yaml
**required_linear_history** and **required_pull_request_reviews** were mistakenly nested when they should have been at the same level. 
Since every PR merge notifies INFRA, I fixed the config right away. Hope we can get this merged soon to minimize the noise.
=> chore(github): Fix the incorrect configuration in .asf.yaml

NOTICE
I couldn't find a detailed definition from ASF on this, but it's okay. In short, it’s related to the validity of intellectual property rights. 
Modern laws may define this differently, but adding the latest NOTICE year is a common practice.
FYI 
https://en.wikipedia.org/wiki/Copyright_notice#Reasons_to_include_an_optional_copyright_notice
https://opensource.stackexchange.com/questions/6389/how-do-the-years-specified-in-a-copyright-statement-work
=> chore(NOTICE): Update NOTICE year to 2025

.github/workflows/ci.yml
According to the description in #702 , Using ubuntu-22.04 can allow the CI to run successfully again. 
Change c++ CI from ubuntu-latest to ubuntu-22.04
yes
no
=> fix(ci): Change ubuntu version of GitHub action from ubuntu-latest to ubuntu-22.04

cpp/examples/high_level_writer_example.cc, cpp/src/graphar/high-level/edges_builder.cc, cpp/src/graphar/high-level/edges_builder.h, cpp/src/graphar/high-level/vertices_builder.h, cpp/src/graphar/writer_util.h, cpp/test/test_arrow_chunk_writer.cc, cpp/test/test_builder.cc
=> feat(c++): Allow setting WriterOptions in high-level writer APIs

cpp/examples/high_level_writer_example.cc, cpp/src/graphar/arrow/chunk_writer.cc, cpp/src/graphar/high-level/vertices_builder.cc, cpp/src/graphar/high-level/vertices_builder.h, cpp/src/graphar/types.h, cpp/test/test_multi_property.cc
Implemented multi-properties in high-level writer (sub-issue of #660).
Add an API that allows `multi-properties` to be added directly through `v.AddProperty()`, and validate the `Cardinality` and `DataType` at the time of addition. 
yes, in `test_multi_property`
yes
=> feat(c++): support build multi-properties in high-level API

.github/workflows/ci.yml, cpp/Brewfile, cpp/README.md
description in #724 
Since Homebrew does not support direct installation of older versions of `apache-arrow`, modifying the Brewfile won't solve the issue. However, we can install a specific version using the following steps:
```bash
git clone https://github.com/Homebrew/homebrew-core.git --depth 1 
cd homebrew-core
git fetch origin b76848f98196f6dd9d3c4e6f71d030da84d22ce8
git checkout b76848f98196f6dd9d3c4e6f71d030da84d22ce8
brew install ./Formula/a/apache-arrow.rb
```
This command can install `apache-arrow 20.0.0_1`, which is the most recent version known to be compatible with the current codebase.
**This is a temporary solution**. Later, we need to find a more elegant way to manage Arrow version, or upgrade the codebase to be compatible with the latest Arrow version.
=> fix(ci): install arrow 20.0.0_1 with brewfile(temporary soluation)

cpp/src/graphar/high-level/graph_reader.cc, cpp/src/graphar/high-level/graph_reader.h
related to #774 
1. using `const &` and `std::move` to reduce copies
2. remove unnecessary `std::move`
yes
no
=> chore(c++): reduce copies in graph_reader.h and remove unnecessary `std::move`
